### ISSUE TITLE
Unexpected symbol nead '<\127>'

### ISSUE THREAD

**Issue by doronbehar** [hoelzro/linotify#18]
I get an error when I `require('inotfy')`:
```
error loading module 'inotify' from file '/home/doron/.luarocks/lib/lua/5.3/inotify.so':
        /home/doron/.luarocks/lib/lua/5.3/inotify.so:1: unexpected symbol near '<\127>'
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: in ?
```
I installed `inotofy.so` with `luarocks` but I get it even when use `inotify.so` compiled from the git repository.

**Comment by hoelzro** [comment]
@doronbehar Thanks for the report! What does your `package.path` and `package.cpath` look like before you call `require`?

**Comment by doronbehar** [comment]
`package.path`:
```
/home/doron/.luarocks/share/lua/5.3/?.lua;/home/doron/.luarocks/share/lua/5.3/?/init.lua;/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;/usr/lib/lua/5.3/?.lua;/usr/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua;/home/doron/.luarocks/lib/lua/5.3/?.so;/usr/lib/lua/5.3/?.so;/usr/lib/lua/5.3/loadall.so;./?.so;/usr/share/awesome/lib/?/init.lua;/usr/share/awesome/lib/?.lua;/home/doron/.luarocks/lib/lua/5.3/?.so;/usr/lib/lua/5.3/?.so;/usr/lib/lua/5.3/loadall.so;./?.so
```
`package.cpath`:
```
/home/doron/.luarocks/lib/lua/5.3/?.so;/usr/lib/lua/5.3/?.so;/usr/lib/lua/5.3/loadall.so;./?.so
```

**Comment by hoelzro** [comment]
Ah, ok - that makes sense! So you have a bunch of `?.so` paths in your `package.path` - you want those in your `package.cpath` instead.  Lua will interpret any file found via `package.path` as Lua source code; shared libraries like `inotify.so` are loaded via `package.cpath`.

**Comment by doronbehar** [comment]
Yea that fixed it, thanks!
